### ISSUE TITLE
Remove Track from PlayList

### ISSUE THREAD

**Issue by mp1pro** [JayWebz/jammming#1]
Unable to remove a track from playList due to the props not being passed properly in 'PlayList'. You had
`<Tracklist tracks={this.props.playlistTracks} onRemove={this.onRemove}/>`

when the onRemove attribute should be passed as a prop like

`<TrackList tracks={this.props.playlistTracks} onRemove={this.props.onRemove} />`

**Comment by JayWebz** [comment]
That was working earlier, but I guess I changed it last minute without realizing what I did in an effort to clean it up for submission. It's all fixed now though: `<Tracklist tracks={this.props.playlistTracks} onRemove={this.props.onRemove}/>`
