### ISSUE TITLE
Reset playListName

### ISSUE THREAD

**Issue by mp1pro** [JayWebz/jammming#2]
The reason why the playlistName does not reset when the 'save to spotify' button is clicked is because the value of the input that displays the name is not set to `this.props.playlistName` like so;

`<input value={'New Playlist'} onChange={this.handleNameChange}/>`

It should be like this instead;

`<input value={this.props.playlistName} onChange={this.handleNameChange}/>`

in playList.js

**Comment by JayWebz** [comment]
Thanks for the tip Marvin! I updated Playlist.js to call props now.
