### ISSUE TITLE
Summary

### ISSUE THREAD

**Issue by mp1pro** [JayWebz/jammming#3]
The project ran well. No major errors were detected. I would suggest running and testing the functionalities of the app before publishing to github. Ensure that all the features are working correctly. Since the only errors was in relation to state and props, here is a great document to cover;

https://facebook.github.io/react-vr/docs/components-props-and-state.html

**Comment by JayWebz** [comment]
Thank you Marvin! I'll review this and check out the additional bonus activities provided in the lessons too.
